### ISSUE TITLE
Error  Creating User 401 Unauthorized

### ISSUE THREAD

**Issue by Jordanirabor** [pusher/chatkit-server-go#9]
I keep getting this error even when I try to authenticate the User.

Any help here?

**Comment by Jordanirabor** [comment]
This is the complete error:

Error  Creating User 401 Unauthorized: {"error":"authentication/jwt/expiry_too_far_ahead","error_description":"Token exp (expiry) may be no more than 86400s in the future"}

**Comment by Jordanirabor** [comment]
No, I'm not doing that.

**Comment by Jordanirabor** [comment]
I get that error no matter what I do

**Comment by mdpye** [comment]
Can you check the date and time on the machine you are generating the token on please? The code is pretty straigthforward, so a drifting clock seems the most likely cause.

**Comment by hamchapman** [comment]
Yep, it works fine for me.

If you try the `authenticate.go` example in the `auth_example` directory of the repo (once you've set the `CHATKIT_INSTANCE_LOCATOR` and `CHATKIT_KEY` env vars) you should end up with a token.

If you then try a curl command like this:

```
curl -X SUBSCRIBE https://us1.pusherplatform.io/services/chatkit/v1/YOUR_INSTANCE_ID/users -H 'Authorization: Bearer THE_GENERATED_TOKEN'
```

then you should find that the request succeeds.

Note that in the path you need the instance ID (not locator!). All that means is the last part of the instance locator.

So if your instance locator is `us1:v1:abc-123` then the instance ID is just the `abc-123` part.

Let me know how you get on with that and if it works or not.

**Comment by BenPope** [comment]
Closing as stale. Please re-open with more details if this is still an issue on the latest version.
